const {launchBrowser,outputDir,loadFixtureAccess}=require('./support.cjs');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await launchBrowser();
  try{
    await loadFixtureAccess();
    const context=await browser.newContext({viewport:{width:1280,height:1000}});
    let game=JSON.parse(await fs.readFile(path.join(outputDir,'emoji-game.json'),'utf8'));
    let actions=0;
    await context.route('**/*',async route=>{
      const url=new URL(route.request().url());
      if(url.hostname!=='emoji-preview.local')throw Error('Unexpected network request');
      if(route.request().method()!=='GET'){actions++;return route.abort();}
      let json;
      if(url.pathname==='/api/auth/me')json={user:{id:'emoji-qa',name:'Emoji preview'},csrf_token:'fixture-only'};
      else if(url.pathname==='/api/config')json={player_available:true,player_mode:'test',model:'display-fixture',reasoning:'none'};
      else if(url.pathname==='/api/games/emoji-qa')json=game;
      if(json)return route.fulfill({json});
      const relative=url.pathname==='/'?'index.html':url.pathname.replace(/^\/static\//,'');
      if(!['index.html','app.js','style.css','pieces.js'].includes(relative))return route.fulfill({status:404,body:''});
      await route.fulfill({path:path.resolve(__dirname,'../../static',relative),contentType:relative.endsWith('.js')?'text/javascript':relative.endsWith('.css')?'text/css':'text/html'});
    });
    const page=await context.newPage();
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    const toggle=page.locator('#emoji-toggle'),input=page.locator('#message-input'),picker=page.locator('#emoji-picker');
    await page.goto('http://emoji-preview.local/?game=emoji-qa');
    await toggle.waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.getElementById('emoji-toggle').disabled);
    await input.fill('Good move!');
    await input.evaluate(el=>el.setSelectionRange(5,5));
    await toggle.click();await picker.getByRole('button',{name:'Smile',exact:true}).click();
    assert.equal(await input.inputValue(),'Good 🙂move!');
    assert.equal(await input.evaluate(el=>el.selectionStart),7);
    assert.equal(await page.locator('#message-count').textContent(),'12 / 2000');
    assert.equal(await page.locator('#send-message').isEnabled(),true);
    await input.fill('Nice try');await input.evaluate(el=>el.setSelectionRange(5,8));
    await toggle.click();await picker.getByRole('button',{name:'Wink',exact:true}).click();
    assert.equal(await input.inputValue(),'Nice 😉');
    await input.fill('x'.repeat(1999));
    await toggle.click();await picker.getByRole('button',{name:'Smile',exact:true}).click();
    assert.equal((await input.inputValue()).length,1999);
    assert.match(await page.locator('#toast').textContent(),/won’t fit/);
    await input.fill('x'.repeat(1998));
    await toggle.click();await picker.getByRole('button',{name:'Chess pawn',exact:true}).click();
    assert.equal((await input.inputValue()).length,2000);
    assert.ok((await input.inputValue()).endsWith('♟️'));
    await toggle.click();await page.keyboard.press('Escape');
    assert.equal(await picker.isHidden(),true);
    assert.equal(await toggle.evaluate(el=>el===document.activeElement),true);
    await toggle.click();await input.click();assert.equal(await picker.isHidden(),true);
    await input.fill('Well played! ');
    await toggle.focus();await page.keyboard.press('Enter');
    assert.equal(await picker.getByRole('button',{name:'Smile',exact:true}).evaluate(el=>el===document.activeElement),true);
    await page.keyboard.press('Enter');assert.equal(await input.inputValue(),'Well played! 🙂');
    await toggle.click();
    await page.locator('.chat-card').screenshot({path:path.join(outputDir,'emoji-desktop.png')});
    await page.setViewportSize({width:390,height:844});
    await page.locator('.composer').scrollIntoViewIfNeeded();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('.chat-card').screenshot({path:path.join(outputDir,'emoji-mobile.png')});
    game={...game,status:'finished',termination:'resignation',result:'0-1',version:1};
    await page.reload();await page.waitForFunction(()=>document.getElementById('message-input').placeholder.startsWith('Discuss'));
    assert.equal(await toggle.isEnabled(),true);
    await toggle.click();await picker.getByRole('button',{name:'Handshake',exact:true}).click();
    assert.equal(await input.inputValue(),'🤝');
    game={...game,status:'suspended',version:2};
    await page.reload();await page.waitForFunction(()=>!document.getElementById('resume-game').hidden);
    assert.equal(await toggle.isDisabled(),true);assert.equal(await picker.isHidden(),true);
    assert.equal(actions,0);assert.deepEqual(errors,[]);
    console.log('Emoji smoke checks passed: caret, replacement, limit, keyboard, dismissal, desktop/mobile, postgame, suspended; no messages sent or live services accessed.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
