const {launchBrowser,outputDir,fixtureOrigin,loadFixtureAccess}=require('./support.cjs');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const base=fixtureOrigin;
async function idle(page){await page.waitForFunction(()=>!document.getElementById('generate-archive').disabled);}
async function select(page,variant){await page.locator('#archive-variant-'+variant).click();await idle(page);assert.equal(await page.locator('#archive-variant-'+variant).getAttribute('aria-selected'),'true');}
async function generate(page){await page.locator('#generate-archive').click();await idle(page);await page.locator('#archive-ready').waitFor();return page.locator('#download-archive').getAttribute('href');}
async function download(page,filename){const promised=page.waitForEvent('download');await page.locator('#download-archive').click();const d=await promised;const target=path.join(outputDir,filename);await d.saveAs(target);return target;}
async function listing(request){const r=await request.get(base+'/api/public-replays');assert.equal(r.status(),200);return r.json();}
(async()=>{
 const browser=await launchBrowser();
 try{
  const access=await loadFixtureAccess();
  const context=await browser.newContext({viewport:{width:1280,height:1100},acceptDownloads:true});
  await context.addCookies([{name:'astra_session',value:access.cookie,url:base,sameSite:'Strict',httpOnly:true}]);
  const anonymous=await browser.newContext();const request=anonymous.request;
  const endpoint=base+'/api/games/'+access.game,headers={Origin:base,'X-CSRF-Token':access.csrf};
  // Only the dedicated fixture account is ever mutated. Start each run clean.
  for(const variant of ['moves','chat'])assert.ok((await context.request.delete(endpoint+'/archive?variant='+variant,{headers})).ok());
  const legacyResponse=await context.request.post(endpoint+'/share',{headers,data:{include_commentary:true}});
  assert.ok(legacyResponse.ok());const legacyUrl=(await legacyResponse.json()).url;
  const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error'&&!m.location().url.endsWith('/favicon.ico'))errors.push(m.text());});
  await page.goto(base+'/?game='+access.game);await page.locator('#save-replay').click();await idle(page);
  assert.equal(await page.locator('#archive-legacy').isVisible(),true);
  assert.equal(await page.locator('#open-archive-legacy').getAttribute('href'),legacyUrl);
  assert.equal(await page.locator('#copy-archive-legacy').isEnabled(),true);
  assert.equal(await page.locator('#archive-variant-moves').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#archive-commentary').count(),0);
  const movesDownload=await generate(page);
  const noChatFile=await download(page,'variants-moves.html'),noChat=await fs.readFile(noChatFile,'utf8');
  assert.ok(!noChat.includes('PRIVATE_CHAT_SENTINEL'));assert.ok(!noChat.includes(access.game));
  await select(page,'chat');assert.equal(await page.locator('#archive-ready').isHidden(),true);
  const chatDownload=await generate(page),chatFile=await download(page,'variants-chat.html');
  assert.ok((await fs.readFile(chatFile,'utf8')).includes('PRIVATE_CHAT_SENTINEL'));
  assert.equal(await (await context.request.get(movesDownload)).text(),noChat);
  assert.match(await page.locator('#archive-variant-moves-status').textContent(),/Saved/);
  assert.equal(await page.locator('#archive-listed').isChecked(),false);
  await page.locator('#share-archive').click();await idle(page);
  const chatUrl=await page.locator('#open-archive-public').getAttribute('href');
  assert.equal((await listing(request)).total,0);assert.equal((await request.get(chatUrl)).status(),200);
  await select(page,'moves');assert.equal(await page.locator('#download-archive').getAttribute('href'),movesDownload);
  await page.locator('#archive-listed').check();await page.locator('#share-archive').click();await idle(page);
  let movesUrl=await page.locator('#open-archive-public').getAttribute('href');
  let list=await listing(request);assert.equal(list.total,1);assert.equal(list.games[0].include_commentary,false);
  assert.equal(new URL(list.games[0].public_url,base).href,movesUrl);
  assert.equal(await (await request.get(movesUrl)).text(),noChat);
  await page.locator('#disable-archive-link').click();await idle(page);
  assert.equal((await request.get(movesUrl)).status(),404);
  assert.equal(await page.locator('#archive-legacy').isVisible(),true);assert.equal((await request.get(legacyUrl)).status(),200);
  assert.equal(await (await context.request.get(movesDownload)).text(),noChat);
  await page.locator('#archive-listed').check();await page.locator('#share-archive').click();await idle(page);
  movesUrl=await page.locator('#open-archive-public').getAttribute('href');
  await page.reload();await page.locator('#save-replay').click();await idle(page);
  assert.match(await page.locator('#archive-variant-chat-status').textContent(),/Saved/);
  assert.equal(await page.locator('#archive-listed').isChecked(),true);
  await select(page,'chat');assert.equal(await page.locator('#archive-listed').isChecked(),false);
  assert.equal(await page.locator('#download-archive').getAttribute('href'),chatDownload);
  await page.locator('#list-archive-public').click();await idle(page);
  list=await listing(request);assert.equal(list.total,1);assert.equal(list.games[0].include_commentary,true);
  assert.equal(new URL(list.games[0].public_url,base).href,chatUrl);
  assert.equal((await request.get(movesUrl)).status(),200);
  await page.locator('#remove-archive-public').click();await idle(page);
  list=await listing(request);assert.equal(list.total,1);assert.equal(list.games[0].include_commentary,false);
  assert.equal((await request.get(chatUrl)).status(),200);
  await page.locator('#list-archive-public').click();await idle(page);
  const oldShared=await (await request.get(chatUrl)).text();
  const updatedChatDownload=await generate(page);assert.notEqual(updatedChatDownload,chatDownload);
  assert.equal(await (await request.get(chatUrl)).text(),oldShared);
  assert.equal(await (await context.request.get(movesDownload)).text(),noChat);
  const beforeRelist=await (await context.request.get(endpoint+'/archive?variant=chat')).json();
  await page.locator('#remove-archive-public').click();await idle(page);
  const relistRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url()===endpoint+'/archive/share');
  await page.locator('#list-archive-public').click();
  assert.deepEqual((await relistRequest).postDataJSON(),{archive_id:beforeRelist.shared_archive_id,listed:true});
  await idle(page);assert.equal(await page.locator('#open-archive-public').getAttribute('href'),chatUrl);
  assert.equal(await (await request.get(chatUrl)).text(),oldShared);
  assert.equal((await request.get(legacyUrl)).status(),200);
  await page.locator('#archive-dialog').screenshot({path:path.join(outputDir,'variants-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#archive-dialog').screenshot({path:path.join(outputDir,'variants-mobile.png')});
  const replay=await anonymous.newPage();replay.on('pageerror',e=>errors.push(e.message));
  await replay.goto(chatUrl);await replay.locator('#last').click();assert.ok((await replay.locator('#chat-list').textContent()).includes('POSTGAME_SENTINEL'));
  assert.equal(await replay.evaluate(()=>window.XSS),undefined);
  await replay.locator('#first').click();assert.ok(!(await replay.locator('#chat-list').textContent()).includes('POSTGAME_SENTINEL'));
  await replay.goto(pathToFileURL(chatFile).href);await replay.locator('#last').click();assert.match(await replay.locator('#position-count').textContent(),/4 \/ 4/);
  await page.locator('#delete-archive').click();assert.match(await page.locator('#archive-delete-question').textContent(),/With chat/);
  await page.locator('#cancel-delete-archive').click();assert.equal((await request.get(chatUrl)).status(),200);
  await page.locator('#delete-archive').click();await page.locator('#confirm-delete-archive').click();await idle(page);
  assert.equal(await page.locator('#archive-ready').isHidden(),true);assert.equal((await request.get(chatUrl)).status(),404);
  assert.equal((await context.request.get(updatedChatDownload)).ok(),false);
  assert.equal((await request.get(movesUrl)).status(),200);assert.equal(await (await context.request.get(movesDownload)).text(),noChat);
  assert.equal(await page.locator('#archive-legacy').isVisible(),true);assert.equal((await request.get(legacyUrl)).status(),200);
  list=await listing(request);assert.equal(list.total,1);assert.equal(list.games[0].include_commentary,false);
  await select(page,'moves');await page.locator('#delete-archive').click();await page.locator('#confirm-delete-archive').click();await idle(page);
  assert.equal((await request.get(movesUrl)).status(),404);assert.equal((await listing(request)).total,0);
  assert.equal(await page.locator('#archive-legacy').isVisible(),true);assert.equal((await request.get(legacyUrl)).status(),200);
  await page.locator('#disable-archive-legacy').click();await idle(page);
  assert.equal(await page.locator('#archive-legacy').isVisible(),false);assert.equal((await request.get(legacyUrl)).status(),404);
  await page.reload();await page.locator('#save-replay').click();await idle(page);
  assert.match(await page.locator('#archive-variant-moves-status').textContent(),/Not saved/);
  assert.match(await page.locator('#archive-variant-chat-status').textContent(),/Not saved/);
  const original=await (await context.request.get(base+'/api/games/'+access.game)).json();
  assert.equal(original.status,'finished');assert.equal(original.moves.length,4);assert.equal(original.messages.length,6);
  assert.deepEqual(errors,[]);
  console.log('Two-variant browser flow passed: independent downloads/URLs; chat opt-in; listing precedence/fallback; refresh isolation; older snapshot relisting; legacy-link survival and revocation; per-version deletion/cancellation; reload; game intact; offline playback; synchronized chat/XSS; desktop/mobile. Disposable fixture only.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
